import React, { useEffect, useState, useRef } from 'react';
import { decodeAudioData } from '../services/geminiService';
import { Play, Square } from 'lucide-react';
import Button from './Button';

interface AudioPlayerProps {
  base64Audio: string | undefined;
}

const AudioPlayer: React.FC<AudioPlayerProps> = ({ base64Audio }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const audioContextRef = useRef<AudioContext | null>(null);
  const sourceNodeRef = useRef<AudioBufferSourceNode | null>(null);

  useEffect(() => {
    // Cleanup on unmount
    return () => {
      if (sourceNodeRef.current) {
        sourceNodeRef.current.stop();
      }
      if (audioContextRef.current) {
        audioContextRef.current.close();
      }
    };
  }, []);

  const playAudio = async () => {
    if (!base64Audio) return;

    try {
      if (!audioContextRef.current || audioContextRef.current.state === 'closed') {
        audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)();
      }

      // Resume context if suspended (browser policy)
      if (audioContextRef.current.state === 'suspended') {
        await audioContextRef.current.resume();
      }

      setIsPlaying(true);
      const audioBuffer = await decodeAudioData(base64Audio, audioContextRef.current);
      
      const source = audioContextRef.current.createBufferSource();
      source.buffer = audioBuffer;
      source.connect(audioContextRef.current.destination);
      
      source.onended = () => setIsPlaying(false);
      
      source.start();
      sourceNodeRef.current = source;

    } catch (error) {
      console.error("Error playing audio:", error);
      setIsPlaying(false);
    }
  };

  const stopAudio = () => {
    if (sourceNodeRef.current) {
      sourceNodeRef.current.stop();
      setIsPlaying(false);
    }
  };

  if (!base64Audio) return null;

  return (
    <div className="flex items-center gap-4 p-4 bg-orange-50 rounded-lg border border-orange-100">
      <div className="bg-orange-100 p-3 rounded-full">
        {isPlaying ? (
           <div className="flex space-x-1 h-4 items-end">
             <div className="w-1 bg-orange-500 animate-[bounce_1s_infinite] h-2"></div>
             <div className="w-1 bg-orange-500 animate-[bounce_1.2s_infinite] h-4"></div>
             <div className="w-1 bg-orange-500 animate-[bounce_0.8s_infinite] h-3"></div>
           </div>
        ) : (
          <Play size={20} className="text-orange-600 ml-1" />
        )}
      </div>
      <div className="flex-1">
        <p className="text-sm font-medium text-orange-900">Listen to the phrase</p>
        <p className="text-xs text-orange-700">Audio generated by Gemini</p>
      </div>
      <Button 
        variant={isPlaying ? "danger" : "primary"} 
        onClick={isPlaying ? stopAudio : playAudio}
        className="min-w-[100px]"
      >
        {isPlaying ? "Stop" : "Play"}
      </Button>
    </div>
  );
};

export default AudioPlayer;